package by.training.carrent.controller.command;

public enum CommandType {
	
	SIGN_UP_PAGE,
	TO_SIGN_UP_PAGE_COMMAND,
	CODE_ENTRY_PAGE,
	TO_CODE_ENTERY_PAGE_COMMAND,
	SIGN_IN_PAGE,
	TO_SIGN_IN_PAGE_COMMAND,
	MAKE_ORDER_PAGE,
	TO_MAKE_ORDER_PAGE_COMMAND,
	PAYMENT_ENTRY_PAGE,
	
	TO_HOME_PAGE_COMMAND,
	SIGN_OUT_COMMAND,
	
	TO_PERSONAL_PROFILE_PAGE_COMMAND,
	TO_ERROR_PAGE,
	
	CHANGE_LANGUAGE_TO_ENGLISH_COMMAND,
	CHANGE_LANGUAGE_TO_RUSSIAN_COMMAND,
	
	TO_CHANGE_FIRST_NAME_PAGE_COMMAND,
	CHANGE_FIRST_NAME_PAGE,
	TO_CHANGE_LAST_NAME_PAGE_COMMAND,
	CHANGE_LAST_NAME_PAGE,
	TO_CHANGE_PHONE_NUMBER_PAGE_COMMAND,
	CHANGE_PHONE_NUMBER_PAGE,
	TO_CHANGE_EMAIL_PAGE_COMMAND,
	CHANGE_EMAIL_PAGE,
	TO_CHANGE_PASSWORD_PAGE_COMMAND,
	CHANGE_PASSWORD_PAGE
}
