package by.training.carrent.controller.command;

public enum CommandType {
	SIGN_UP_PAGE,
	TO_SIGN_UP_PAGE_COMMAND,
	CODE_ENTRY_PAGE,
	TO_CODE_ENTERY_PAGE_COMMAND,
	
	TO_ERROR_PAGE,
	
	CHANGE_LANGUAGE_TO_ENGLISH_COMMAND,
	CHANGE_LANGUAGE_TO_RUSSIAN_COMMAND,
	
	TO_HOME_PAGE_COMMAND
	
	
}
